version: '3.1'

services:
   web:
      build: .
      volumes:
         - .:/src
      depends_on:
        - "db"
      ports:
         - 3333:3333
      networks:
         - backend
      environment:
         WAIT_HOSTS: db:27017
         MONGODB_URL: mongodb://db:27017/app_development
         MONGODB_USER: mongo
         MONGODB_PASSWORD: mongo
      networks:
         - backend

   db:
      image: mongo
      hostname: db
      container_name: challenge_database
      restart: always
      environment:
         MONGO_INITDB_ROOT_PASSWORD: mongo
         MONGO_INITDB_ROOT_USERNAME: mongo
      ports:
         - 27017:27017
      networks:
         - backend

networks:
   backend:
    driver: bridge